package:
  name: pythonnet
  version: "2.4.0.dev0"

build:
  skip: True  # [not win]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - clr

about:
  home: https://github.com/pythonnet/pythonnet
  license: MIT
  license_file: LICENSE
